PlaysTvAppId = 'DLKWBYCZNnBpDL4WOIRkCLFtDI7tO2RsOIGZ'
PlaysTvKey = '9exhOxYiMA4l0TH_utz5LAHH4Ii2ANbX'
GamesDataPath = '../Data/games.pkl'
GamesDir = '../Data'
PlaysTvLinesPerVid = 5
PlaysTvLinesPerPage = 2000
Ylogin = 'pavel.dudko2016@yandex.com'
Ypassword = 'Zt2w47kH'
VideosDirPath = '../Data/videos'
MongoHost = 'localhost'
MongoPort = 27017
MongoUserName = ''
MongoPassword = ''
MongoDb = 'gamevideos'
NeoHost = 'localhost:7474'
NeoLog = 'neo4j'
NeoPass = 'refuse'
twitter_consumer_key = "4MqIMsUyXiOb7En65t973cRYK"
twitter_consumer_secret = "dNoS2k8pWrB74x7HJzEU9plSfj7FgfUtZGRbUyoKF9pyCB9uy5"
twitter_access_key = "509969813-p00p4cVEOXX1mMXFMh3DqYN5Lsjpp8apoEHAe0dk"
twitter_access_secret = "DEVwEgH4of4DgRsHDVPdV9mDN0a5RKKFYSknLr4OknUPM"
twitter_account_name = "ProveYourSkillz"
twitter_account_gamers = ["IamDiamond_23", "MinidukeLoL", "Falco_lol", "RafaL0L", "Th3AntonioGG", "Minitroupax", "werlyb_", "PePiiNeRO", "ElOjoNinja", "MoryoLoL"]
ReplyLen = 5

